# service.sh - run a profile as a login service with auto-reconnect
# macOS: launchd user agent (~/Library/LaunchAgents)
# Linux: systemd user unit (~/.config/systemd/user)
#
# Service mode runs openconnect in the FOREGROUND under the service manager.
# `vpn-up start` returns an outcome code (outcome.sh), and the top-level
# dispatch (vpn-up.command) maps it through service_exit_code() before
# exiting: exit 0 tells the supervisor to STOP (a permanent condition —
# missing dependency, bad config, sudo/helper policy refusal), any other exit
# tells it to RESTART (everything self-healing, including a dropped tunnel).
# The in-process rate limiter (outcome.sh: admit_attempt) is what actually
# throttles unattended re-authentication — KeepAlive/Restart's own timers are
# just the respawn floor for the cheap, no-budget cases (network down,
# already running), not the retry policy. Requirements:
#   - a passwordless sudoers rule for openconnect (see README; it grants
#     effective root to the invoking user — see SECURITY.md "Known limitations")
#   - the profile's password stored in the secrets backend
#   - a non-interactive 2FA method (push/phone/sms — not passcode)

LAUNCH_AGENT_DIR="${VPN_UP_LAUNCH_AGENT_DIR:-$HOME/Library/LaunchAgents}"
SYSTEMD_USER_DIR="${VPN_UP_SYSTEMD_DIR:-${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user}"
SERVICE_LABEL_PREFIX="com.sorinipate.vpn-up"

# Escape &, <, > for XML/plist/unit content. Done via sed, not bash ${//}
# substitution: under bash >= 5.2 `patsub_replacement` is on by default, so an
# unescaped `&` in a ${var//pat/repl} replacement expands to the matched text
# (e.g. ${s//</&lt;} yields "<lt;", not "&lt;"). sed's `\&` is an unambiguous
# literal ampersand across all bash versions. `&` must be escaped first.
_xml_escape() { printf '%s' "$1" | sed -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g'; }

_service_path_for() {
  local key; key="$(profile_key "$1")" || return 1
  if [ "$(uname)" = "Darwin" ]; then
    printf '%s/%s.%s.plist' "$LAUNCH_AGENT_DIR" "$SERVICE_LABEL_PREFIX" "$key"
  else
    printf '%s/vpn-up-%s.service' "$SYSTEMD_USER_DIR" "$key"
  fi
}

# Today's exact slug-only formula, kept verbatim -- used only to locate a
# pre-collision-fix service file for verified migration/cleanup, never to
# compute a path this code writes to.
_service_legacy_path_for() {
  local slug; slug="$(profile_slug "$1")"
  if [ "$(uname)" = "Darwin" ]; then
    printf '%s/%s.%s.plist' "$LAUNCH_AGENT_DIR" "$SERVICE_LABEL_PREFIX" "$slug"
  else
    printf '%s/vpn-up-%s.service' "$SYSTEMD_USER_DIR" "$slug"
  fi
}

# Best-effort extraction of the profile name embedded in an already-written
# plist/unit, so a legacy-named file can be positively attributed before
# this code ever unloads or deletes it. Empty output means "could not prove
# ownership" -- callers must treat that the same as "wrong profile": refuse.
_service_definition_profile() {
  local path="$1"
  [ -f "$path" ] || return 0
  if [ "$(uname)" = "Darwin" ]; then
    plutil -extract 'ProgramArguments.3' raw -o - "$path" 2>/dev/null
  else
    sed -n 's/^Description=VPN Up for OpenConnect (\(.*\))$/\1/p' "$path" | head -1
  fi
}

# Path to a profile's service log (StandardOutPath/StandardErrorPath on
# macOS). Mirrors profile_log_file()'s shape.
_service_log_file() {
  local key; key="$(profile_key "$1")" || return 1
  printf '%s/logs/service.%s.log' "$DATA_DIR" "$key"
}

# Unload/stop the service at PATH and VERIFY it's actually no longer
# loaded/active -- not `launchctl unload ... || true` and hope. Distinguishes
# *confirmed stopped* from *couldn't ask*: a query failure (launchd/systemd
# unreachable) is never read as proof of inactivity. Returns 0 only when
# confirmed stopped (a diagnostic is already printed on any other outcome);
# callers must not proceed past a non-zero return.
_service_stop_and_verify() {
  local path="$1" profile="$2"
  if [ "$(uname)" = "Darwin" ]; then
    local label; label="$(basename "$path" .plist)"
    launchctl unload -w "$path" 2>/dev/null
    local list_out list_rc
    list_out="$(launchctl list 2>/dev/null)"; list_rc=$?
    if [ "$list_rc" -ne 0 ]; then
      print_danger "Cannot query launchd to confirm the service for '%s' stopped.\n" "$profile"
      return 1
    fi
    # Exact last-field match against launchctl list's own PID\tStatus\tLabel
    # format -- not `grep -qF "$label"` anywhere in the output, which could
    # false-match "foo" against "foobar". Safe to do exactly here (unlike
    # ps-rendered argv elsewhere in this codebase): the Label is entirely
    # self-generated by _service_path_for/profile_key and guaranteed
    # whitespace-free by profile_slug's own substitution, not parsed out of
    # an arbitrary external command line.
    if printf '%s\n' "$list_out" | awk -v label="$label" '$NF == label { found=1 } END { exit !found }'; then
      print_danger "Could not establish that the service for '%s' is stopped.\n" "$profile"
      return 1
    fi
  else
    systemctl --user disable --now "$(basename "$path")" 2>/dev/null
    # systemd documents `systemctl is-active`'s exit code only as "0 if
    # active, non-zero otherwise" -- not a specific code for "inactive" --
    # so this queries the actual state and switches on its value instead of
    # inferring meaning from an exit code.
    local state state_rc
    state="$(systemctl --user show --property=ActiveState --value "$(basename "$path")" 2>/dev/null)"; state_rc=$?
    if [ "$state_rc" -ne 0 ] || [ -z "$state" ]; then
      print_danger "Cannot query systemd to confirm the service for '%s' stopped.\n" "$profile"
      return 1
    fi
    case "$state" in
      inactive|failed) : ;;
      *)
        print_danger "Could not establish that the service for '%s' is stopped (state: %s).\n" "$profile" "$state"
        return 1
        ;;
    esac
  fi
  return 0
}

# Generate the launchd plist for a profile to stdout. Computes its key
# (Label, log path) BEFORE emitting any heredoc output -- a failure must
# produce nothing, not a partial file.
write_launch_agent_plist() {
  local profile="$1" key log_file bash_bin oc_dir
  key="$(profile_key "$profile")" || return 1
  log_file="$(_service_log_file "$profile")" || return 1
  bash_bin="${BASH:-$(command -v bash)}"
  oc_dir="$(dirname "$(command -v openconnect)")"
  cat <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${SERVICE_LABEL_PREFIX}.${key}</string>
  <key>ProgramArguments</key>
  <array>
    <string>$(_xml_escape "$bash_bin")</string>
    <string>$(_xml_escape "${PROGRAM_PATH}/${PROGRAM_NAME}")</string>
    <string>start</string>
    <string>$(_xml_escape "$profile")</string>
  </array>
  <key>EnvironmentVariables</key>
  <dict>
    <key>VPN_UP_SERVICE</key>
    <string>1</string>
    <key>PATH</key>
    <string>$(_xml_escape "$oc_dir"):/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
  </dict>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <dict>
    <key>SuccessfulExit</key>
    <false/>
  </dict>
  <key>ThrottleInterval</key>
  <integer>30</integer>
  <key>StandardOutPath</key>
  <string>$(_xml_escape "$log_file")</string>
  <key>StandardErrorPath</key>
  <string>$(_xml_escape "$log_file")</string>
</dict>
</plist>
PLIST
}

# Generate the systemd user unit for a profile to stdout.
write_systemd_unit() {
  local profile="$1" bash_bin oc_dir
  bash_bin="${BASH:-$(command -v bash)}"
  oc_dir="$(dirname "$(command -v openconnect)")"
  cat <<UNIT
[Unit]
Description=VPN Up for OpenConnect (${profile})
After=network-online.target
Wants=network-online.target
# Defence in depth only: the in-process rate limiter (outcome.sh) owns normal
# retry policy and keeps the process alive for the whole delay, so ordinary
# operation can never approach this. It only fires if a bug crashes vpn-up
# before it reaches the gate -- headroom set above VPN_RC_NO_NETWORK's own
# 30s restart cadence (10 starts in 300s would trip a StartLimitBurst=10).
StartLimitIntervalSec=300
StartLimitBurst=20

[Service]
Type=simple
ExecStart=${bash_bin} ${PROGRAM_PATH}/${PROGRAM_NAME} start "${profile}"
Environment=VPN_UP_SERVICE=1
Environment=PATH=${oc_dir}:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
# on-failure, not always: exit 0 (service_exit_code(), outcome.sh) means a
# permanent condition -- STOP, don't restart. Every other exit restarts.
Restart=on-failure
RestartSec=30

[Install]
WantedBy=default.target
UNIT
}

# Sanity checks before installing a service for a profile.
_service_preflight() {
  local profile="$1"
  profiles_xml_ok || return 1
  if ! profile_exists "$profile"; then
    print_danger "Unknown profile '%s'.\n" "$profile"
    return 1
  fi
  local authmode
  authmode="$(xmlstarlet sel -t -m "//VPN[name=$(xpath_literal "$profile")]" -v 'authMode | authmode' "$PROFILES_FILE" 2>/dev/null)"
  if [ "$authmode" = sso ]; then
    print_danger "Profile '%s' uses SSO (interactive browser); it cannot run as a login service.\n" "$profile"
    return 1
  fi
  # Cache-independent, and routed through the right probe for whichever path
  # applies: `sudo -n -v` here would read a possibly-warm credential cache
  # (this project's own past bug, fixed everywhere else) rather than policy,
  # and would prove nothing about a specific command being NOPASSWD anyway.
  command -v vu_legacy_grant_state >/dev/null 2>&1 || . "${PROGRAM_PATH}/helperinstall.sh"
  local _svc_ready=0
  if helper_mode_available; then
    _svc_ready=1
  elif vu_tools_resolve >/dev/null 2>&1; then
    local _oc; _oc="$(command -v openconnect 2>/dev/null)"
    [ -n "$_oc" ] && [ "$(vu_legacy_grant_state "$_oc")" = yes ] && _svc_ready=1
  fi
  if [ "$_svc_ready" != 1 ]; then
    print_warning "No proven passwordless sudo. Service mode requires a sudoers rule for the privileged helper (preferred: %s install-helper --passwordless) or for openconnect (see README); the service will fail until one exists. NOTE: a raw-openconnect rule grants effective root to your account (see SECURITY.md).\n" "${DISPLAY_NAME}"
  fi
  local clientcert clientkey
  clientcert="$(xmlstarlet sel -t -m "//VPN[name=$(xpath_literal "$profile")]" -v 'clientCertificate | clientcertificate' "$PROFILES_FILE" 2>/dev/null)"
  clientkey="$(xmlstarlet sel -t -m "//VPN[name=$(xpath_literal "$profile")]" -v 'clientKey | clientkey' "$PROFILES_FILE" 2>/dev/null)"
  # A cert-only profile needs no stored password, so only warn about a missing
  # password when there is no client certificate to authenticate with. Routed
  # through _secret_check (core.sh), not a raw secrets_get, so a temporary
  # backend error is distinguished from "genuinely no password stored" --
  # otherwise a transient Keychain/Secret Service/vault failure here reads as
  # "no password" and produces a misleading warning during installation, the
  # same tri-state distinction the runtime preflight already makes.
  if [ -z "$clientcert" ]; then
    _secret_check "$profile" password >/dev/null
    case $? in
      1) print_warning "No stored password for '%s'. Store one first: %s set-secret '%s' password\n" "$profile" "${DISPLAY_NAME}" "$profile" ;;
      2) print_warning "Could not check the secrets store for a stored password for '%s' (temporary backend error); the service will re-check at runtime.\n" "$profile" ;;
    esac
  fi
  local duo
  duo="$(xmlstarlet sel -t -m "//VPN[name=$(xpath_literal "$profile")]" -v 'duo2FAMethod | duoMethod' "$PROFILES_FILE" 2>/dev/null)"
  if [ "$duo" = "passcode" ]; then
    print_danger "Profile '%s' uses a Duo passcode (interactive); it cannot run as a service.\n" "$profile"
    return 1
  fi
  # TOTP is non-interactive (the code is generated from a stored seed), so it CAN
  # run as a service — but only if the seed is stored and oathtool is available.
  local tokenmode
  tokenmode="$(xmlstarlet sel -t -m "//VPN[name=$(xpath_literal "$profile")]" -v 'tokenMode | tokenmode' "$PROFILES_FILE" 2>/dev/null)"
  if [ "$tokenmode" = totp ]; then
    _secret_check "$profile" token_secret >/dev/null
    case $? in
      1)
        print_danger "Profile '%s' uses TOTP but has no stored secret; a service can't prompt. Store it first: %s set-secret '%s' token_secret\n" "$profile" "${DISPLAY_NAME}" "$profile"
        return 1 ;;
      2)
        print_warning "Could not check the secrets store for a stored TOTP secret for '%s' (temporary backend error); the service will re-check at runtime.\n" "$profile" ;;
    esac
    command -v oathtool >/dev/null 2>&1 || print_warning "'oathtool' not found; the TOTP service will fail until it's installed (brew install oath-toolkit | apt-get install oathtool).\n"
  fi
  # Client-certificate auth works as a service only when no interactive prompt is
  # needed. A PKCS#11 certificate OR key needs a stored PIN (key_password) --
  # checking only the certificate (an earlier version of this function) missed
  # the equally valid case of a file-path certificate paired with a PKCS#11
  # key; _pkcs11_pin_needed (core.sh) checks both, and is the same predicate
  # the setup wizard and the runtime preflight/phase-4 fetch use, so there is
  # one definition of "does this profile need a PKCS#11 PIN", not several. A
  # file-based key must be unencrypted (a passphrase prompt has no TTY under
  # launchd/systemd).
  if [ -n "$clientcert" ]; then
    if _pkcs11_pin_needed "$clientcert" "$clientkey"; then
      _secret_check "$profile" key_password >/dev/null
      case $? in
        1) print_warning "Profile '%s' uses a PKCS#11 client certificate; a service can't enter the PIN. Store it first: %s set-secret '%s' key_password\n" "$profile" "${DISPLAY_NAME}" "$profile" ;;
        2) print_warning "Could not check the secrets store for a stored PKCS#11 PIN for '%s' (temporary backend error); the service will re-check at runtime.\n" "$profile" ;;
      esac
    else
      print_warning "Profile '%s' uses a client-certificate file. If the private key is passphrase-protected it cannot run as a service (no TTY to prompt); use an unencrypted 0600 key.\n" "$profile"
    fi
  fi
  return 0
}

# Load/start the (already-activated) definition at PATH. Sets LOADED_OK=1 on
# success. Linux: reloads the daemon first (unit content just changed on
# disk); if systemctl isn't present at all, the write itself is treated as
# the whole job (nothing more this function can verify).
_service_load() {
  local path="$1" profile="$2"
  LOADED_OK=0
  if [ "$(uname)" = "Darwin" ]; then
    launchctl load -w "$path" && LOADED_OK=1
  else
    if command -v systemctl >/dev/null 2>&1; then
      # A failed daemon-reload means systemd hasn't seen the file's new
      # content -- proceeding to `enable --now` anyway risks (re)activating
      # whatever it still has cached (a stale or even the just-replaced old
      # unit), which could report LOADED_OK=1 for content that was never
      # actually loaded. Abort before enabling anything in that case.
      if systemctl --user daemon-reload; then
        systemctl --user enable --now "$(basename "$path")" && LOADED_OK=1
      else
        print_danger "systemctl --user daemon-reload failed for '%s'; not enabling it against a possibly stale daemon state.\n" "$profile"
      fi
    else
      print_warning "Wrote %s; systemctl not found, enable it manually.\n" "$path"
      LOADED_OK=1
    fi
  fi
  # Outcome is communicated via LOADED_OK, not the return status: this is
  # called as a bare statement (service_install, both on the activation path
  # and mid-rollback), so if this function's own return status reflected a
  # launchctl/systemctl failure, that bare call would abort the caller under
  # errexit (bats' own included) before the LOADED_OK check -- and rollback
  # -- ever ran. Same bug class as the service_install ending fixed above.
  return 0
}

# Restore whatever service_install's step 2 stopped, after a later step
# failed -- verifying both that the file ends up back in place and that it
# actually reloads, rather than assuming either. An unverified "Restored"
# message would be worse than none: it would tell the operator their VPN
# service is fine when it might not be. RESTORE_PATH empty means nothing
# was stopped (a fresh install, nothing previously active) -- nothing to do.
# TARGET is where a non-legacy restore belongs; a legacy pair is reloaded at
# its own, never-moved path instead (RESTORE_IS_LEGACY=1).
_service_restore_previous() {
  local target="$1" restore_path="$2" restore_is_legacy="$3" profile="$4"
  [ -n "$restore_path" ] || return 0
  local reload_path="$restore_path"
  if [ "$restore_is_legacy" != 1 ]; then
    reload_path="$target"
    if [ "$restore_path" != "$target" ] && ! mv -f "$restore_path" "$target" 2>/dev/null; then
      print_danger "Could not move the previous service definition for '%s' back into place (still at %s); restore it manually.\n" "$profile" "$restore_path"
      return 1
    fi
  fi
  _service_load "$reload_path" "$profile" >/dev/null 2>&1
  if [ "$LOADED_OK" != 1 ]; then
    print_danger "Restored the previous service definition for '%s' at %s but it did not reload; start it manually.\n" "$profile" "$reload_path"
    return 1
  fi
  print_warning "Restored the previous working service for '%s'.\n" "$profile"
  return 0
}

# Staged, verified, checked, rollback-safe activation. Never writes directly
# into a possibly-live $target, never leaves a previously working service
# stopped if the new one fails to load.
service_install() {
  local profile="$1"
  [ -n "$profile" ] || { echo "Usage: ${DISPLAY_NAME} service install <profile>" >&2; return 1; }
  _service_preflight "$profile" || return 1

  local target; target="$(_service_path_for "$profile")" || { print_danger "Could not determine the service path for '%s'.\n" "$profile"; return 1; }
  local staged="${target}.new"
  if [ "$(uname)" = "Darwin" ]; then mkdir -p "$LAUNCH_AGENT_DIR"; else mkdir -p "$SYSTEMD_USER_DIR"; fi

  # 1) Generate + validate into a sibling file. Nothing live touched yet.
  # ($staged is a fixed name shared by any concurrent `service install` for
  # the SAME profile -- accepted as a known, low-severity limitation given
  # this is a rare, manually-run command, rather than adding mktemp-based
  # staging or a serializing lock for it.)
  if [ "$(uname)" = "Darwin" ]; then
    write_launch_agent_plist "$profile" > "$staged" || { rm -f "$staged"; print_danger "Could not generate the launch agent definition for '%s'.\n" "$profile"; return 1; }
    plutil -lint "$staged" >/dev/null 2>&1 || { rm -f "$staged"; print_danger "Generated launch agent definition for '%s' is invalid; nothing changed.\n" "$profile"; return 1; }
  else
    write_systemd_unit "$profile" > "$staged" || { rm -f "$staged"; print_danger "Could not generate the systemd unit for '%s'.\n" "$profile"; return 1; }
    [ -s "$staged" ] || { rm -f "$staged"; print_danger "Generated systemd unit for '%s' is empty; nothing changed.\n" "$profile"; return 1; }
  fi

  # 2) Identify + stop whatever's currently active, so it can be restored on
  # failure. restore_path always tracks where the just-stopped definition
  # CURRENTLY lives -- before a backup-rename attempt succeeds, that's still
  # $target itself -- so _service_restore_previous can find it regardless of
  # which later step fails.
  local restore_path="" restore_is_legacy=0
  if [ -f "$target" ]; then
    local old_path="${target}.old"
    if [ -e "$old_path" ]; then
      # A previous install attempt crashed between backing up and finishing
      # -- that leftover is the only recovery copy; blindly overwriting it
      # would destroy it. Refuse outright.
      rm -f "$staged"
      print_danger "An unresolved backup from a previous install attempt exists at %s. Resolve it manually (verify which of %s / %s is the working definition, keep that one, remove the other), then retry. Nothing was changed.\n" \
        "$old_path" "$target" "$old_path"
      return 1
    fi
    if ! _service_stop_and_verify "$target" "$profile"; then
      rm -f "$staged"
      print_warning "Nothing was changed for '%s'.\n" "$profile"
      return 1
    fi
    restore_path="$target"
    if mv -f "$target" "$old_path"; then
      restore_path="$old_path"
    else
      print_danger "Stopped the existing service for '%s' but could not back it up; restoring it.\n" "$profile"
      rm -f "$staged"
      _service_restore_previous "$target" "$restore_path" 0 "$profile"
      return 1
    fi
  else
    local legacy; legacy="$(_service_legacy_path_for "$profile")"
    if [ -f "$legacy" ]; then
      local legacy_owner; legacy_owner="$(_service_definition_profile "$legacy")"
      if [ "$legacy_owner" = "$profile" ]; then
        print_warning "Migrating '%s' from the legacy service naming.\n" "$profile"
        if ! _service_stop_and_verify "$legacy" "$profile"; then
          rm -f "$staged"
          print_warning "Nothing was changed for '%s'.\n" "$profile"
          return 1
        fi
        restore_path="$legacy"
        restore_is_legacy=1
      elif [ -n "$legacy_owner" ]; then
        print_warning "A legacy-named service file exists at %s but belongs to a different profile ('%s'); leaving it untouched.\n" "$legacy" "$legacy_owner"
      else
        # Unverifiable ownership must fail closed, the same as an
        # unattributable legacy pid/state pair does in
        # resolve_profile_runtime_files: this file could in fact BE the
        # requested profile's own pre-collision-fix service, and installing
        # over it blind risks two registrations (old + new) for the same
        # VPN, one of them invisible to this code.
        rm -f "$staged"
        print_danger "A legacy-named service file exists at %s but its owning profile could not be verified; refusing to install until this is resolved. Check manually and remove or rename it if it does not belong to '%s'.\n" "$legacy" "$profile"
        return 1
      fi
    fi
  fi

  # 3) Atomically activate.
  if ! mv -f "$staged" "$target"; then
    rm -f "$staged"
    print_danger "Could not activate the service definition for '%s'.\n" "$profile"
    _service_restore_previous "$target" "$restore_path" "$restore_is_legacy" "$profile"
    return 1
  fi

  # 4) Load/start it.
  _service_load "$target" "$profile"

  if [ "$LOADED_OK" != 1 ]; then
    print_danger "Wrote %s but could not load/start it; rolling back.\n" "$target"
    if [ "$(uname)" = "Darwin" ]; then
      launchctl unload -w "$target" 2>/dev/null
    else
      command -v systemctl >/dev/null 2>&1 && systemctl --user disable --now "$(basename "$target")" 2>/dev/null
    fi
    rm -f "$target"
    _service_restore_previous "$target" "$restore_path" "$restore_is_legacy" "$profile"
    return 1
  fi

  print_success "Installed and loaded service for '%s': %s\n" "$profile" "$target"
  print_warning "The VPN will now connect at login and auto-reconnect if it drops. Remove with: %s service uninstall '%s'\n" "${DISPLAY_NAME}" "$profile"
  # 5) Only now, having proven the replacement actually loads, remove the
  # now-superseded backup/legacy file. `[ -n ... ] && rm ...` must not be the
  # function's last statement: it returns 1 (false) whenever restore_path is
  # empty -- the common fresh-install case -- which would make this whole,
  # otherwise-successful function report failure to any caller checking its
  # exit status directly (bats' own errexit included).
  if [ -n "$restore_path" ]; then
    rm -f "$restore_path"
  fi
  return 0
}

service_uninstall() {
  local profile="$1"
  [ -n "$profile" ] || { echo "Usage: ${DISPLAY_NAME} service uninstall <profile>" >&2; return 1; }
  local target; target="$(_service_path_for "$profile")" || { print_danger "Could not determine the service path for '%s'.\n" "$profile"; return 1; }
  if [ ! -f "$target" ]; then
    local legacy; legacy="$(_service_legacy_path_for "$profile")"
    if [ -f "$legacy" ]; then
      local legacy_owner; legacy_owner="$(_service_definition_profile "$legacy")"
      if [ "$legacy_owner" = "$profile" ]; then
        print_warning "Found a legacy-named service for '%s'; removing it.\n" "$profile"
        target="$legacy"
      else
        print_warning "A legacy-named service file exists at %s but does not appear to belong to '%s' (%s); leaving it untouched.\n" \
          "$legacy" "$profile" "${legacy_owner:-owner unverifiable}"
        print_warning "No service installed for '%s' (%s).\n" "$profile" "$target"
        return 0
      fi
    else
      print_warning "No service installed for '%s' (%s).\n" "$profile" "$target"
      return 0
    fi
  fi
  # abort without removing $target if it can't be positively confirmed
  # stopped -- deleting the definition file while the job might still be
  # loaded under it would orphan a running service with no on-disk record
  # of it, which is worse than leaving the file in place and reporting the
  # failure.
  _service_stop_and_verify "$target" "$profile" || return 1
  rm -f "$target"
  if [ -e "$target" ]; then
    print_danger "Stopped the service for '%s' but could not remove its definition file (%s); left in place.\n" "$profile" "$target"
    return 1
  fi
  print_success "Removed service for '%s'.\n" "$profile"
  print_warning "If the VPN is still connected, stop it with: %s stop '%s'\n" "${DISPLAY_NAME}" "$profile"
}

service_status() {
  local found=0 f
  if [ "$(uname)" = "Darwin" ]; then
    for f in "$LAUNCH_AGENT_DIR/$SERVICE_LABEL_PREFIX".*.plist; do
      [ -e "$f" ] || continue
      found=1
      local label; label="$(basename "$f" .plist)"
      if launchctl list 2>/dev/null | grep -qF "$label"; then
        print_success "loaded   %s\n" "$f"
      else
        print_warning "unloaded %s\n" "$f"
      fi
    done
  else
    for f in "$SYSTEMD_USER_DIR"/vpn-up-*.service; do
      [ -e "$f" ] || continue
      found=1
      local unit; unit="$(basename "$f")"
      if command -v systemctl >/dev/null 2>&1 && systemctl --user is-active --quiet "$unit" 2>/dev/null; then
        print_success "active   %s\n" "$f"
      else
        print_warning "inactive %s\n" "$f"
      fi
    done
  fi
  [ "$found" -eq 0 ] && print_warning "No VPN services installed.\n"
  return 0
}